spring:
  application:
    name: eureka-server
#  利用spring-security组件，鉴权
  security:
    user:
      name: hero
      password: 123456

server:
  port: 8761

eureka:
  client:
#   由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为 false
    fetch-registry: false
#   由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
  server:
#   关闭自我保护机制（一旦进入保护模式，Eureka Server将会尝试保护其服务的注册表中的信息，不再删除服务注册表中的数据。当网络故障恢复后，该Eureka Server节点会自动退出保护模式。）
    enable-self-preservation: false
#   服务列表默认清理时间间隔
    eviction-interval-timer-in-ms: 5000

